### ISSUE TITLE
openvpn on vps bond to achieve main connection speed on vpn,  help  please

### ISSUE THREAD

**Issue by offbeatshotz** [onemarcfifty/openvpn-bonding#2]
hi saw your fork in search.
i have 500mbps and 1 gbps vps
im trying to achieve at least about 440 mbps when connected to vpn on vps 
openvpn seems to only give me 40-60 mbps which is unacceptable and unsatisfied to pay for 500mbps and only able to use 40-60 mbps.
would your script work for me? to achieve a bond on my server, i thought openvpn already bonds.
any help or things i could run on my centos 8 server openvpn already installed

**Comment by onemarcfifty** [comment]
Hi, that depends on a number of factors which are partially out of your/my control. Check the speed to the vps you are connecting to by downloading a large file (e.g. over sftp/scp). This is the max speed that you can get over the line. You may need to chose another vps, Second check the speed from your csp to the internet. ssh into the VPS and do something like wget http://www.ovh.net/files/100Mb.dat in order to check your VP's speed. If both speeds are above what you expect then you might improve things using this solution.

**Comment by offbeatshotz** [comment]
> Hi, that depends on a number of factors which are partially out of your/my control. Check the speed to the vps you are connecting to by downloading a large file (e.g. over sftp/scp). This is the max speed that you can get over the line. You may need to chose another vps, Second check the speed from your csp to the internet. ssh into the VPS and do something like wget http://www.ovh.net/files/100Mb.dat in order to check your VP's speed. If both speeds are above what you expect then you might improve things using this solution.

thanks for replying back.
results from what you wanted me to enter :
`HTTP request sent, awaiting response... 200 OK
Length: 12500000 (12M) [application/octet-stream]
Saving to: ‘100Mb.dat’

100Mb.dat                100%[==================================>]  11.92M  10.6MB/s    in 1.1s

2020-09-18 14:02:23 (10.6 MB/s) - ‘100Mb.dat’ saved [12500000/12500000]`

still dont know how to solve using this solution.
i have done a speedtest ooakla speedtest cli on the server with vpn off.
was 1gbps both upload and download.
my connection is download 500 mbps  upload 24 mbps.
let me know if i can do your  bonding method as my issue is when vpn connected on router to vps i dont even get my main connection speed anymore its 50 mbps, not trying to obtain 1gbps i know i cant achieve more than main connection. just want close to 470 mbps, when i was using openvpn to vps on 100mbps server before and my connection was 100 mbps before, i would get only 20-30 mbps drop. so i dont see why im losing so much now

**Comment by onemarcfifty** [comment]
Maybe check the latest version - there have been some bugs

**Comment by onemarcfifty** [comment]
So the ovh file download was done from the vps right? That means your VPS has 100 mbit into the internet. What speed figures do you get sftp a file directly from the vps to your home? Have you tried switching encryption off?

**Comment by offbeatshotz** [comment]
So the ovh file download was done from the vps right? it was on the vps meaning i wasnt connected to vpn to vps when doing speedtest was down from ssh.

 
That means your VPS has 100 mbit into the internet.  the speedtest showed it as a 1gbps download and upload, read the above.

 
What speed figures do you get sftp a file directly from the vps to your home? from vps to my home is 50 mbps. doesnt make sense as i have 500 mbps

 
Have you tried switching encryption off? ive tried numerous things lower encryption, changing to tap instead of tun, tried using wireguard and mikrotik.

**Comment by onemarcfifty** [comment]
So the 50mbps from your vps to your home are with sftp or similar but _without_ vpn right? If you only get 50 mbps to there then you can not expect better bandwidth over the vpn...

**Comment by offbeatshotz** [comment]
> So the 50mbps from your vps to your home are with sftp or similar but _without_ vpn right? If you only get 50 mbps to there then you can not expect better bandwidth over the vpn...

i dont have home connection of 50 mbps NO..
my home connection is indeed 500 mbps
when on vpn at home, vpn is on vps.  i get 50 mbps.
the vps is 1gbps
i hope this is not confusing now?

**Comment by onemarcfifty** [comment]
I understand that your home connection is 500mb.
I understand that your vps has 100mb

What is missing is a measurement of the chunk between your home and the vps:

Home-vps-internet

Do an sftp download from your vps to your home server and measure the speed without vpn

**Comment by onemarcfifty** [comment]
You may watch https://youtu.be/I08A4-PWawk for explanation

**Comment by offbeatshotz** [comment]
> I understand that your home connection is 500mb.
> I understand that your vps has 100mb
> 
> What is missing is a measurement of the chunk between your home and the vps:
> 
> Home-vps-internet
> 
> Do an sftp download from your vps to your home server and measure the speed without vpn

im confused why are you thinking my vps is only 100 mbps? i did a test it is is 1gbps.
i followed the video you sent i did already see it but this time watched it closer, i know im doing it wrong. do you got discord?
discord me @ norge#7035

**Comment by onemarcfifty** [comment]
The above wget command shows 10MByte/sec which is approximately 100mbit per second.

**Comment by offbeatshotz** [comment]
> The above wget command shows 10MByte/sec which is approximately 100mbit per second.

i dont know why it would be 100 mbps since i did a vps speed test with ssh it said it was 1gbps.
chat with me on discord ill share my screen

**Comment by onemarcfifty** [comment]
Ok my friend, we can do that. I am currently at a place with very low bandwidth and also I need to figure out how to setup and use discord. Might also provide this at a fixed time to everybody. Which country/timezone are you in?

**Comment by offbeatshotz** [comment]
eastern america

**Comment by onemarcfifty** [comment]
Ok so 3pm my time wold be roughly 9am your time - I will come back to you - give me a couple of days

**Comment by offbeatshotz** [comment]
> Ok so 3pm my time wold be roughly 9am your time - I will come back to you - give me a couple of days

ok so monday i assume

**Comment by offbeatshotz** [comment]
> Ok so 3pm my time wold be roughly 9am your time - I will come back to you - give me a couple of days

its been a few days didnt hear from you.
everything alright?
can you still help me

**Comment by onemarcfifty** [comment]
I will - just time is the issue. Just need to figure out a couple of things. Please keep in mind that I am only doing this on week ends and as time permits. I will be in touch.

**Comment by offbeatshotz** [comment]
> I will - just time is the issue. Just need to figure out a couple of things. Please keep in mind that I am only doing this on week ends and as time permits. I will be in touch.

let me know this weekend

**Comment by onemarcfifty** [comment]
Hi sorry, I've tried to join you a couple of times on discord, without success. Furthermore the issue seems to be rather related to speed measurement than function of the scripts - I will close this now but feel free to contact me on discord to arrange on a time.
