### ISSUE TITLE
problem adding routes

### ISSUE THREAD

**Issue by shanelecuyer** [onemarcfifty/openvpn-bonding#4]
Debian 10 inside an lxc in proxmox. I had to mknod and allow cgroups for the /dev/net/tun device. These ppp devices are dsl modems in bridge mode on vlan1000 and vlan 1001 through 2 switches. I cant seem to figure the problem out

https://user-images.githubusercontent.com/9566851/99039976-55b0d700-2556-11eb-84b1-26975db8caaa.jpg

https://user-images.githubusercontent.com/9566851/99041352-c0fba880-2558-11eb-9adb-ca212f059f61.jpg

**Comment by onemarcfifty** [comment]
Hi Shane, as per our communication on Discord I believe this is solved.
