### ISSUE TITLE
i dont know why, but i cant connect from my client to the server

### ISSUE THREAD

**Issue by nirbk** [onemarcfifty/openvpn-bonding#5]
i did all the steps exactly as described in the video.
i use ubuntu 20.4 and the server is also ubuntu 20.4
added the key... checked that the devices are legit...
all is updated. no firewall to block the connections... i just cant figure it out what is missing...
from the client i cant ping even the server... only my local host.
please help.

**Comment by nirbk** [comment]
ok after long hours of trying... i think i know what was the problem... i think it was the copy and paste of the ta.key content from the server to my client.
hope that was the case so i can restore it when i will want to do again the process...

great script and great work... you helped me allot :)

**Comment by onemarcfifty** [comment]
Glad you got it solved.
